[project]
name = "frateto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.8.0",
    "litellm>=1.74.8",
    "pandas>=2.3.1",
    "python-dotenv>=1.1.1",
]
